# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(n):
    """
    Fibonacci sequence generator
    """
    a = 0
    b = 1
    c = 1
    while c < n:
        c = a + b
        a, b = b, c
        yield c


def even_sum(num):
    """
    Summing numbers according to the task.
    """
    x = fibonacci(num)
    sum = 0
    number = 0

    while number < num:

        number = next(x)

        if number > num:
            break
        elif number % 2 == 0:
            sum += number
        else:
            pass
    return sum


sum = even_sum(4000000)

print(sum)
